version: '3'

services:
  app:
    build: .
    container_name: messageapp
    working_dir: /usr/src/app
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - app:/usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm start

  postgres:
    image: postgres:12
    container_name: messageapp_db
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: messagetest
      POSTGRES_PASSWORD: myPostgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ne191131@senshu-u.jp
      PGADMIN_DEFAULT_PASSWORD: 4431a
    ports:
      - 8083:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  app:
  postgres:
  pgadmin: